### ISSUE TITLE
Test coverage for `settingsSlice`

### ISSUE THREAD

**Issue by karczewskiPiotr** [vnLab-Lodz/PubLab#137]
All of the slice's reducers  need to be tested.

![image](https://user-images.githubusercontent.com/34404855/143442380-7101a859-ec7e-4838-adea-934455e547d8.png)

Have a peek at the #130 for a small example of the test.

**Comment by Bart1019** [comment]
On the main branch settingsSlice looks a little bit different. This one above is on the other branches. Should I change this file or leave is as it is?

**Comment by karczewskiPiotr** [comment]
> On the main branch settingsSlice looks a little bit different. This one above is on the other branches. Should I change this file or leave is as it is?

Test what is on the main branch, thanks. 🙏

**Comment by Bart1019** [comment]
![image](https://user-images.githubusercontent.com/58557921/144109439-d70d5b48-46b3-465c-b971-bc00964b05f0.png)

I started to test this slice, line 8 throws, that 'app' is undefined, but as i change const to this exemplary string, test pass. Should i leave test that fails or check what is the problem in the slice?

**Comment by karczewskiPiotr** [comment]
> ![image](https://user-images.githubusercontent.com/58557921/144110016-312a8738-4deb-4504-9928-d97715caceb0.png)
> 
> I started to test this slice, line 8 throws, that 'app' is undefined, but as i change const to this exemplary string, test pass. Should i leave test that fails or check what is the problem in the slice?

You can pull the changes from the main branch and it should be all good now.
