### ISSUE TITLE
Fix filesystem actions failures

### ISSUE THREAD

**Issue by LostInStatic** [vnLab-Lodz/PubLab#196]
## Description

When performing file actions with incorrect path, the application throws an error on electron's main process. This makes the interface only display an error message and prevents the user from correcting the mistake.  I've noticed two handlers causing this behavior:

- `settings:read`: When the `publab-settings.json` is missing from PubLab's appdata folder or the whole folder is not yet generated ; seems like the read should just be omitted if the file is not found.
- `publications:find-local`: When the default folder path is wrong. It is possible to set the wrong path during the first time setup by picking a folder and then changing the path manually ; probably the input should be validated before the state update as in `AppSettings` view.

IMO the handler errors should be displayed in a way that does not unnecessarily interfere with the application functionality as often as possible.  The root cause could be just a bad input or stale data, easily correctable by the user. However, simply updating the logic/validation will address the currently occurring problems - the holistic approach might as well be discussed later.

**Comment by karczewskiPiotr** [comment]
Will be tackled after #198 so that notifications can possibly be used to display some info.
