### ISSUE TITLE
Line endings in repositories

### ISSUE THREAD

**Issue by LostInStatic** [vnLab-Lodz/PubLab#218]
## Description

While implementing #214 I stumbled upon an issue best described [here](https://github.com/isomorphic-git/isomorphic-git/issues/1275). (tldr; every file is modified after clone because of different line endings)  It does not seem very hard to solve, but I would like to discuss the exact approach.

**Comment by karczewskiPiotr** [comment]
Previous attempt at fixing this was mentioned in [this](https://github.com/vnLab-Lodz/PubLab/pull/217#pullrequestreview-1027206050) comment

**Comment by karczewskiPiotr** [comment]
@LostInStatic it seem like this config for templates does the trick.

```
* eol=lf

*.png text=auto
*.jpg text=auto
*.jpeg text=auto
*.gif text=auto
*.webp text=auto
*.mp4 text=auto
```
> 🔍 Note: I haven't pushed this to the actual templates nor the publications yet.

I have added you to [this](https://github.com/karczewskiPiotr/lines) repo as a collaborator. Can you accept the invite, set is as active in the app and see if the commits view will show no changes?

**Comment by karczewskiPiotr** [comment]
@LostInStatic `.gitattributes` config has been updated in all PaaW templates and repositories. 

For already cloned repositories it is advised to run the following commands after the update.

```sh
git rm --cached -r .
git reset --hard
```

I have run into some issues with font files sometimes not resetting the line endings. Safest way to update is to clone the project via PubLab, which then works 100% of the time by the looks of it. Anyways, a rare case for an actual user of the app to already have a project cloned.

With all that said, I am closing this issue. ✅
