### ISSUE TITLE
Changing language on login screen causes error in publications:find-remote

### ISSUE THREAD

**Issue by LostInStatic** [vnLab-Lodz/PubLab#229]
## Description

![electron_TNWoV9YREc](https://user-images.githubusercontent.com/23729453/181194460-1fe87230-677b-436c-a34f-8c35b56d697d.gif)

After closing the error prompt app seems to function normally, so it is not crucial to fix it right now.

## Error message

```
Error invoking remote method 'publications:find-remote': HttpError: Requires authentication
Call Stack
 EventEmitter.i.send.i.invoke
  js2c/renderer_init.js:71:535
```

## Steps to replicate

1. Get to the login screen
2. Change the language

**Comment by karczewskiPiotr** [comment]
@LostInStatic I can't reproduce this so unsure if this is some edge scenario after logging. However, the error would imply that the api is trying to make a request with a missing token. I made a draft PR with the guard to not fire the octokit request, which should be enough. I'll also come in and fiddle with the ipc events invoked in the `App.tsx` as the guard could also be put there. I'll tag you on the #231 when it's ready for a wee test.
